; AUTOGENERATED FILE; DO NOT EDIT!
;
; This file was generated by asmgen.py, a 6502 code generator sponsored by
; the Player/Missile Podcast. (The sprite compiler is based on HiSprite by
; Quinn Dunki).
;
; The code produced by asmgen is licensed under the Creative Commons
; Attribution 4.0 International (CC BY 4.0), so you are free to use the code in
; this file for any purpose. (The code generator itself is licensed under the
; GPLv3.)

COMPILEDFONT_H1	; A = character, X = column, Y = row; A is clobbered, X&Y are not
	sty scratch_0
	tay
	lda COMPILEDFONT_H1_JMP_HI,y
	sta COMPILEDFONT_H1_JMP+2
	lda COMPILEDFONT_H1_JMP_LO,y
	sta COMPILEDFONT_H1_JMP+1
	ldy scratch_0
	lda hgrtextrow_l,y
	sta hgr_ptr
	lda hgrtextrow_h,y
	sta hgr_ptr+1
	txa
	tay
COMPILEDFONT_H1_JMP
	jmp $ffff


COMPILEDFONT_H1_JMP_HI
	.byte >COMPILEDFONT_H1_0
	.byte >COMPILEDFONT_H1_1
	.byte >COMPILEDFONT_H1_2
	.byte >COMPILEDFONT_H1_3
	.byte >COMPILEDFONT_H1_4
	.byte >COMPILEDFONT_H1_5
	.byte >COMPILEDFONT_H1_6
	.byte >COMPILEDFONT_H1_7
	.byte >COMPILEDFONT_H1_8
	.byte >COMPILEDFONT_H1_9
	.byte >COMPILEDFONT_H1_10
	.byte >COMPILEDFONT_H1_11
	.byte >COMPILEDFONT_H1_12
	.byte >COMPILEDFONT_H1_13
	.byte >COMPILEDFONT_H1_14
	.byte >COMPILEDFONT_H1_15
	.byte >COMPILEDFONT_H1_16
	.byte >COMPILEDFONT_H1_17
	.byte >COMPILEDFONT_H1_18
	.byte >COMPILEDFONT_H1_19
	.byte >COMPILEDFONT_H1_20
	.byte >COMPILEDFONT_H1_21
	.byte >COMPILEDFONT_H1_22
	.byte >COMPILEDFONT_H1_23
	.byte >COMPILEDFONT_H1_24
	.byte >COMPILEDFONT_H1_25
	.byte >COMPILEDFONT_H1_26
	.byte >COMPILEDFONT_H1_27
	.byte >COMPILEDFONT_H1_28
	.byte >COMPILEDFONT_H1_29
	.byte >COMPILEDFONT_H1_30
	.byte >COMPILEDFONT_H1_31
	.byte >COMPILEDFONT_H1_32
	.byte >COMPILEDFONT_H1_33
	.byte >COMPILEDFONT_H1_34
	.byte >COMPILEDFONT_H1_35
	.byte >COMPILEDFONT_H1_36
	.byte >COMPILEDFONT_H1_37
	.byte >COMPILEDFONT_H1_38
	.byte >COMPILEDFONT_H1_39
	.byte >COMPILEDFONT_H1_40
	.byte >COMPILEDFONT_H1_41
	.byte >COMPILEDFONT_H1_42
	.byte >COMPILEDFONT_H1_43
	.byte >COMPILEDFONT_H1_44
	.byte >COMPILEDFONT_H1_45
	.byte >COMPILEDFONT_H1_46
	.byte >COMPILEDFONT_H1_47
	.byte >COMPILEDFONT_H1_48
	.byte >COMPILEDFONT_H1_49
	.byte >COMPILEDFONT_H1_50
	.byte >COMPILEDFONT_H1_51
	.byte >COMPILEDFONT_H1_52
	.byte >COMPILEDFONT_H1_53
	.byte >COMPILEDFONT_H1_54
	.byte >COMPILEDFONT_H1_55
	.byte >COMPILEDFONT_H1_56
	.byte >COMPILEDFONT_H1_57
	.byte >COMPILEDFONT_H1_58
	.byte >COMPILEDFONT_H1_59
	.byte >COMPILEDFONT_H1_60
	.byte >COMPILEDFONT_H1_61
	.byte >COMPILEDFONT_H1_62
	.byte >COMPILEDFONT_H1_63
	.byte >COMPILEDFONT_H1_64
	.byte >COMPILEDFONT_H1_65
	.byte >COMPILEDFONT_H1_66
	.byte >COMPILEDFONT_H1_67
	.byte >COMPILEDFONT_H1_68
	.byte >COMPILEDFONT_H1_69
	.byte >COMPILEDFONT_H1_70
	.byte >COMPILEDFONT_H1_71
	.byte >COMPILEDFONT_H1_72
	.byte >COMPILEDFONT_H1_73
	.byte >COMPILEDFONT_H1_74
	.byte >COMPILEDFONT_H1_75
	.byte >COMPILEDFONT_H1_76
	.byte >COMPILEDFONT_H1_77
	.byte >COMPILEDFONT_H1_78
	.byte >COMPILEDFONT_H1_79
	.byte >COMPILEDFONT_H1_80
	.byte >COMPILEDFONT_H1_81
	.byte >COMPILEDFONT_H1_82
	.byte >COMPILEDFONT_H1_83
	.byte >COMPILEDFONT_H1_84
	.byte >COMPILEDFONT_H1_85
	.byte >COMPILEDFONT_H1_86
	.byte >COMPILEDFONT_H1_87
	.byte >COMPILEDFONT_H1_88
	.byte >COMPILEDFONT_H1_89
	.byte >COMPILEDFONT_H1_90
	.byte >COMPILEDFONT_H1_91
	.byte >COMPILEDFONT_H1_92
	.byte >COMPILEDFONT_H1_93
	.byte >COMPILEDFONT_H1_94
	.byte >COMPILEDFONT_H1_95
	.byte >COMPILEDFONT_H1_96
	.byte >COMPILEDFONT_H1_97
	.byte >COMPILEDFONT_H1_98
	.byte >COMPILEDFONT_H1_99
	.byte >COMPILEDFONT_H1_100
	.byte >COMPILEDFONT_H1_101
	.byte >COMPILEDFONT_H1_102
	.byte >COMPILEDFONT_H1_103
	.byte >COMPILEDFONT_H1_104
	.byte >COMPILEDFONT_H1_105
	.byte >COMPILEDFONT_H1_106
	.byte >COMPILEDFONT_H1_107
	.byte >COMPILEDFONT_H1_108
	.byte >COMPILEDFONT_H1_109
	.byte >COMPILEDFONT_H1_110
	.byte >COMPILEDFONT_H1_111
	.byte >COMPILEDFONT_H1_112
	.byte >COMPILEDFONT_H1_113
	.byte >COMPILEDFONT_H1_114
	.byte >COMPILEDFONT_H1_115
	.byte >COMPILEDFONT_H1_116
	.byte >COMPILEDFONT_H1_117
	.byte >COMPILEDFONT_H1_118
	.byte >COMPILEDFONT_H1_119
	.byte >COMPILEDFONT_H1_120
	.byte >COMPILEDFONT_H1_121
	.byte >COMPILEDFONT_H1_122
	.byte >COMPILEDFONT_H1_123
	.byte >COMPILEDFONT_H1_124
	.byte >COMPILEDFONT_H1_125
	.byte >COMPILEDFONT_H1_126
	.byte >COMPILEDFONT_H1_127
COMPILEDFONT_H1_JMP_LO
	.byte <COMPILEDFONT_H1_0
	.byte <COMPILEDFONT_H1_1
	.byte <COMPILEDFONT_H1_2
	.byte <COMPILEDFONT_H1_3
	.byte <COMPILEDFONT_H1_4
	.byte <COMPILEDFONT_H1_5
	.byte <COMPILEDFONT_H1_6
	.byte <COMPILEDFONT_H1_7
	.byte <COMPILEDFONT_H1_8
	.byte <COMPILEDFONT_H1_9
	.byte <COMPILEDFONT_H1_10
	.byte <COMPILEDFONT_H1_11
	.byte <COMPILEDFONT_H1_12
	.byte <COMPILEDFONT_H1_13
	.byte <COMPILEDFONT_H1_14
	.byte <COMPILEDFONT_H1_15
	.byte <COMPILEDFONT_H1_16
	.byte <COMPILEDFONT_H1_17
	.byte <COMPILEDFONT_H1_18
	.byte <COMPILEDFONT_H1_19
	.byte <COMPILEDFONT_H1_20
	.byte <COMPILEDFONT_H1_21
	.byte <COMPILEDFONT_H1_22
	.byte <COMPILEDFONT_H1_23
	.byte <COMPILEDFONT_H1_24
	.byte <COMPILEDFONT_H1_25
	.byte <COMPILEDFONT_H1_26
	.byte <COMPILEDFONT_H1_27
	.byte <COMPILEDFONT_H1_28
	.byte <COMPILEDFONT_H1_29
	.byte <COMPILEDFONT_H1_30
	.byte <COMPILEDFONT_H1_31
	.byte <COMPILEDFONT_H1_32
	.byte <COMPILEDFONT_H1_33
	.byte <COMPILEDFONT_H1_34
	.byte <COMPILEDFONT_H1_35
	.byte <COMPILEDFONT_H1_36
	.byte <COMPILEDFONT_H1_37
	.byte <COMPILEDFONT_H1_38
	.byte <COMPILEDFONT_H1_39
	.byte <COMPILEDFONT_H1_40
	.byte <COMPILEDFONT_H1_41
	.byte <COMPILEDFONT_H1_42
	.byte <COMPILEDFONT_H1_43
	.byte <COMPILEDFONT_H1_44
	.byte <COMPILEDFONT_H1_45
	.byte <COMPILEDFONT_H1_46
	.byte <COMPILEDFONT_H1_47
	.byte <COMPILEDFONT_H1_48
	.byte <COMPILEDFONT_H1_49
	.byte <COMPILEDFONT_H1_50
	.byte <COMPILEDFONT_H1_51
	.byte <COMPILEDFONT_H1_52
	.byte <COMPILEDFONT_H1_53
	.byte <COMPILEDFONT_H1_54
	.byte <COMPILEDFONT_H1_55
	.byte <COMPILEDFONT_H1_56
	.byte <COMPILEDFONT_H1_57
	.byte <COMPILEDFONT_H1_58
	.byte <COMPILEDFONT_H1_59
	.byte <COMPILEDFONT_H1_60
	.byte <COMPILEDFONT_H1_61
	.byte <COMPILEDFONT_H1_62
	.byte <COMPILEDFONT_H1_63
	.byte <COMPILEDFONT_H1_64
	.byte <COMPILEDFONT_H1_65
	.byte <COMPILEDFONT_H1_66
	.byte <COMPILEDFONT_H1_67
	.byte <COMPILEDFONT_H1_68
	.byte <COMPILEDFONT_H1_69
	.byte <COMPILEDFONT_H1_70
	.byte <COMPILEDFONT_H1_71
	.byte <COMPILEDFONT_H1_72
	.byte <COMPILEDFONT_H1_73
	.byte <COMPILEDFONT_H1_74
	.byte <COMPILEDFONT_H1_75
	.byte <COMPILEDFONT_H1_76
	.byte <COMPILEDFONT_H1_77
	.byte <COMPILEDFONT_H1_78
	.byte <COMPILEDFONT_H1_79
	.byte <COMPILEDFONT_H1_80
	.byte <COMPILEDFONT_H1_81
	.byte <COMPILEDFONT_H1_82
	.byte <COMPILEDFONT_H1_83
	.byte <COMPILEDFONT_H1_84
	.byte <COMPILEDFONT_H1_85
	.byte <COMPILEDFONT_H1_86
	.byte <COMPILEDFONT_H1_87
	.byte <COMPILEDFONT_H1_88
	.byte <COMPILEDFONT_H1_89
	.byte <COMPILEDFONT_H1_90
	.byte <COMPILEDFONT_H1_91
	.byte <COMPILEDFONT_H1_92
	.byte <COMPILEDFONT_H1_93
	.byte <COMPILEDFONT_H1_94
	.byte <COMPILEDFONT_H1_95
	.byte <COMPILEDFONT_H1_96
	.byte <COMPILEDFONT_H1_97
	.byte <COMPILEDFONT_H1_98
	.byte <COMPILEDFONT_H1_99
	.byte <COMPILEDFONT_H1_100
	.byte <COMPILEDFONT_H1_101
	.byte <COMPILEDFONT_H1_102
	.byte <COMPILEDFONT_H1_103
	.byte <COMPILEDFONT_H1_104
	.byte <COMPILEDFONT_H1_105
	.byte <COMPILEDFONT_H1_106
	.byte <COMPILEDFONT_H1_107
	.byte <COMPILEDFONT_H1_108
	.byte <COMPILEDFONT_H1_109
	.byte <COMPILEDFONT_H1_110
	.byte <COMPILEDFONT_H1_111
	.byte <COMPILEDFONT_H1_112
	.byte <COMPILEDFONT_H1_113
	.byte <COMPILEDFONT_H1_114
	.byte <COMPILEDFONT_H1_115
	.byte <COMPILEDFONT_H1_116
	.byte <COMPILEDFONT_H1_117
	.byte <COMPILEDFONT_H1_118
	.byte <COMPILEDFONT_H1_119
	.byte <COMPILEDFONT_H1_120
	.byte <COMPILEDFONT_H1_121
	.byte <COMPILEDFONT_H1_122
	.byte <COMPILEDFONT_H1_123
	.byte <COMPILEDFONT_H1_124
	.byte <COMPILEDFONT_H1_125
	.byte <COMPILEDFONT_H1_126
	.byte <COMPILEDFONT_H1_127

COMPILEDFONT_H1_0
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_2
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_3
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_4
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_5
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$54
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$54
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_6
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$54
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$54
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_7
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$54
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$54
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_8
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_9
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$15
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$15
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_10
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$15
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$15
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_11
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$15
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$15
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_12
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$55
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$55
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_13
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$55
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$55
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_14
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$14
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$55
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$55
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_15
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$2a
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$2a
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_16
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_17
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_18
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_19
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_20
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_21
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_22
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_23
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_24
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_25
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_26
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_27
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_28
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_29
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_30
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$7f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_31
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_32
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_33
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_34
	lda #$b6
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b6
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$a4
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b6
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_35
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$aa
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_36
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$d5
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_37
	lda #$b7
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b7
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_38
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9b
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$ae
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_39
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$88
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_40
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_41
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_42
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_43
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_44
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_45
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_46
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_47
	lda #$e0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$f0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_48
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_49
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_50
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$38
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_51
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_52
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bc
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b6
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_53
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_54
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_55
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_56
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_57
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_58
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_59
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_60
	lda #$f0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$f0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_61
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_62
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_63
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_64
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_65
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_66
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_67
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_68
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_69
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_70
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_71
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_72
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_73
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_74
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_75
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_76
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_77
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_78
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b7
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_79
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_80
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_81
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$a3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$a3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$ab
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$93
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$ae
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_82
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bb
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_83
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_84
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_85
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_86
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_87
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_88
	lda #$33
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9b
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$1e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9b
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$33
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_89
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_90
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_91
	lda #$bc
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bc
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bc
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bc
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_92
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$f0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$e0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_93
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_94
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_95
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$ff
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$ff
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_96
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_97
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_98
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_99
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_100
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_101
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_102
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b6
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_103
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_104
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_105
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_106
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_107
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9b
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9b
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_108
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_109
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_110
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_111
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_112
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_113
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_114
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_115
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$83
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_116
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9f
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b6
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_117
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_118
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_119
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_120
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_121
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b3
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$be
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b0
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_122
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_123
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$87
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_124
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8c
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_125
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$b8
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$9e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$8e
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_126
	lda #$86
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$bf
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$98
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$80
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts
COMPILEDFONT_H1_127
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	lda #$00
	sta (hgr_ptr),y
	clc
	lda #4
	adc hgr_ptr+1
	sta hgr_ptr+1
	ldy scratch_0
	rts




hgrtextrow_l
        .byte $00,$80,$00,$80,$00,$80,$00,$80
        .byte $28,$A8,$28,$A8,$28,$A8,$28,$A8
        .byte $50,$D0,$50,$D0,$50,$D0,$50,$D0
hgrtextrow_h
        .byte $20,$20,$21,$21,$22,$22,$23,$23
        .byte $20,$20,$21,$21,$22,$22,$23,$23
        .byte $20,$20,$21,$21,$22,$22,$23,$23
