; AUTOGENERATED FILE; DO NOT EDIT!
;
; This file was generated by asmgen.py, a 6502 code generator sponsored by
; the Player/Missile Podcast. (The sprite compiler is based on HiSprite by
; Quinn Dunki).
;
; The code produced by asmgen is licensed under the Creative Commons
; Attribution 4.0 International (CC BY 4.0), so you are free to use the code in
; this file for any purpose. (The code generator itself is licensed under the
; GPLv3.)

FASTFONT_H1	; A = character, X = column, Y = row; A is clobbered, X&Y are not
	pha
	lda FASTFONT_H1_JMP_HI,y
	sta FASTFONT_H1_JMP+2
	lda FASTFONT_H1_JMP_LO,y
	sta FASTFONT_H1_JMP+1
	sty scratch_0
	pla
	tay
FASTFONT_H1_JMP
	jmp $ffff


FASTFONT_H1_JMP_HI
	.byte >FASTFONT_H1_0
	.byte >FASTFONT_H1_1
	.byte >FASTFONT_H1_2
	.byte >FASTFONT_H1_3
	.byte >FASTFONT_H1_4
	.byte >FASTFONT_H1_5
	.byte >FASTFONT_H1_6
	.byte >FASTFONT_H1_7
	.byte >FASTFONT_H1_8
	.byte >FASTFONT_H1_9
	.byte >FASTFONT_H1_10
	.byte >FASTFONT_H1_11
	.byte >FASTFONT_H1_12
	.byte >FASTFONT_H1_13
	.byte >FASTFONT_H1_14
	.byte >FASTFONT_H1_15
	.byte >FASTFONT_H1_16
	.byte >FASTFONT_H1_17
	.byte >FASTFONT_H1_18
	.byte >FASTFONT_H1_19
	.byte >FASTFONT_H1_20
	.byte >FASTFONT_H1_21
	.byte >FASTFONT_H1_22
	.byte >FASTFONT_H1_23
FASTFONT_H1_JMP_LO
	.byte <FASTFONT_H1_0
	.byte <FASTFONT_H1_1
	.byte <FASTFONT_H1_2
	.byte <FASTFONT_H1_3
	.byte <FASTFONT_H1_4
	.byte <FASTFONT_H1_5
	.byte <FASTFONT_H1_6
	.byte <FASTFONT_H1_7
	.byte <FASTFONT_H1_8
	.byte <FASTFONT_H1_9
	.byte <FASTFONT_H1_10
	.byte <FASTFONT_H1_11
	.byte <FASTFONT_H1_12
	.byte <FASTFONT_H1_13
	.byte <FASTFONT_H1_14
	.byte <FASTFONT_H1_15
	.byte <FASTFONT_H1_16
	.byte <FASTFONT_H1_17
	.byte <FASTFONT_H1_18
	.byte <FASTFONT_H1_19
	.byte <FASTFONT_H1_20
	.byte <FASTFONT_H1_21
	.byte <FASTFONT_H1_22
	.byte <FASTFONT_H1_23

FASTFONT_H1_0
	lda TransposedFontRow0_0,y
	sta $2000,x
	lda TransposedFontRow0_1,y
	sta $2400,x
	lda TransposedFontRow0_2,y
	sta $2800,x
	lda TransposedFontRow0_3,y
	sta $2c00,x
	lda TransposedFontRow0_4,y
	sta $3000,x
	lda TransposedFontRow0_5,y
	sta $3400,x
	lda TransposedFontRow0_6,y
	sta $3800,x
	lda TransposedFontRow0_7,y
	sta $3c00,x
	ldy scratch_0
	rts
FASTFONT_H1_1
	lda TransposedFontRow0_0,y
	sta $2080,x
	lda TransposedFontRow0_1,y
	sta $2480,x
	lda TransposedFontRow0_2,y
	sta $2880,x
	lda TransposedFontRow0_3,y
	sta $2c80,x
	lda TransposedFontRow0_4,y
	sta $3080,x
	lda TransposedFontRow0_5,y
	sta $3480,x
	lda TransposedFontRow0_6,y
	sta $3880,x
	lda TransposedFontRow0_7,y
	sta $3c80,x
	ldy scratch_0
	rts
FASTFONT_H1_2
	lda TransposedFontRow0_0,y
	sta $2100,x
	lda TransposedFontRow0_1,y
	sta $2500,x
	lda TransposedFontRow0_2,y
	sta $2900,x
	lda TransposedFontRow0_3,y
	sta $2d00,x
	lda TransposedFontRow0_4,y
	sta $3100,x
	lda TransposedFontRow0_5,y
	sta $3500,x
	lda TransposedFontRow0_6,y
	sta $3900,x
	lda TransposedFontRow0_7,y
	sta $3d00,x
	ldy scratch_0
	rts
FASTFONT_H1_3
	lda TransposedFontRow0_0,y
	sta $2180,x
	lda TransposedFontRow0_1,y
	sta $2580,x
	lda TransposedFontRow0_2,y
	sta $2980,x
	lda TransposedFontRow0_3,y
	sta $2d80,x
	lda TransposedFontRow0_4,y
	sta $3180,x
	lda TransposedFontRow0_5,y
	sta $3580,x
	lda TransposedFontRow0_6,y
	sta $3980,x
	lda TransposedFontRow0_7,y
	sta $3d80,x
	ldy scratch_0
	rts
FASTFONT_H1_4
	lda TransposedFontRow0_0,y
	sta $2200,x
	lda TransposedFontRow0_1,y
	sta $2600,x
	lda TransposedFontRow0_2,y
	sta $2a00,x
	lda TransposedFontRow0_3,y
	sta $2e00,x
	lda TransposedFontRow0_4,y
	sta $3200,x
	lda TransposedFontRow0_5,y
	sta $3600,x
	lda TransposedFontRow0_6,y
	sta $3a00,x
	lda TransposedFontRow0_7,y
	sta $3e00,x
	ldy scratch_0
	rts
FASTFONT_H1_5
	lda TransposedFontRow0_0,y
	sta $2280,x
	lda TransposedFontRow0_1,y
	sta $2680,x
	lda TransposedFontRow0_2,y
	sta $2a80,x
	lda TransposedFontRow0_3,y
	sta $2e80,x
	lda TransposedFontRow0_4,y
	sta $3280,x
	lda TransposedFontRow0_5,y
	sta $3680,x
	lda TransposedFontRow0_6,y
	sta $3a80,x
	lda TransposedFontRow0_7,y
	sta $3e80,x
	ldy scratch_0
	rts
FASTFONT_H1_6
	lda TransposedFontRow0_0,y
	sta $2300,x
	lda TransposedFontRow0_1,y
	sta $2700,x
	lda TransposedFontRow0_2,y
	sta $2b00,x
	lda TransposedFontRow0_3,y
	sta $2f00,x
	lda TransposedFontRow0_4,y
	sta $3300,x
	lda TransposedFontRow0_5,y
	sta $3700,x
	lda TransposedFontRow0_6,y
	sta $3b00,x
	lda TransposedFontRow0_7,y
	sta $3f00,x
	ldy scratch_0
	rts
FASTFONT_H1_7
	lda TransposedFontRow0_0,y
	sta $2380,x
	lda TransposedFontRow0_1,y
	sta $2780,x
	lda TransposedFontRow0_2,y
	sta $2b80,x
	lda TransposedFontRow0_3,y
	sta $2f80,x
	lda TransposedFontRow0_4,y
	sta $3380,x
	lda TransposedFontRow0_5,y
	sta $3780,x
	lda TransposedFontRow0_6,y
	sta $3b80,x
	lda TransposedFontRow0_7,y
	sta $3f80,x
	ldy scratch_0
	rts
FASTFONT_H1_8
	lda TransposedFontRow0_0,y
	sta $2028,x
	lda TransposedFontRow0_1,y
	sta $2428,x
	lda TransposedFontRow0_2,y
	sta $2828,x
	lda TransposedFontRow0_3,y
	sta $2c28,x
	lda TransposedFontRow0_4,y
	sta $3028,x
	lda TransposedFontRow0_5,y
	sta $3428,x
	lda TransposedFontRow0_6,y
	sta $3828,x
	lda TransposedFontRow0_7,y
	sta $3c28,x
	ldy scratch_0
	rts
FASTFONT_H1_9
	lda TransposedFontRow0_0,y
	sta $20a8,x
	lda TransposedFontRow0_1,y
	sta $24a8,x
	lda TransposedFontRow0_2,y
	sta $28a8,x
	lda TransposedFontRow0_3,y
	sta $2ca8,x
	lda TransposedFontRow0_4,y
	sta $30a8,x
	lda TransposedFontRow0_5,y
	sta $34a8,x
	lda TransposedFontRow0_6,y
	sta $38a8,x
	lda TransposedFontRow0_7,y
	sta $3ca8,x
	ldy scratch_0
	rts
FASTFONT_H1_10
	lda TransposedFontRow0_0,y
	sta $2128,x
	lda TransposedFontRow0_1,y
	sta $2528,x
	lda TransposedFontRow0_2,y
	sta $2928,x
	lda TransposedFontRow0_3,y
	sta $2d28,x
	lda TransposedFontRow0_4,y
	sta $3128,x
	lda TransposedFontRow0_5,y
	sta $3528,x
	lda TransposedFontRow0_6,y
	sta $3928,x
	lda TransposedFontRow0_7,y
	sta $3d28,x
	ldy scratch_0
	rts
FASTFONT_H1_11
	lda TransposedFontRow0_0,y
	sta $21a8,x
	lda TransposedFontRow0_1,y
	sta $25a8,x
	lda TransposedFontRow0_2,y
	sta $29a8,x
	lda TransposedFontRow0_3,y
	sta $2da8,x
	lda TransposedFontRow0_4,y
	sta $31a8,x
	lda TransposedFontRow0_5,y
	sta $35a8,x
	lda TransposedFontRow0_6,y
	sta $39a8,x
	lda TransposedFontRow0_7,y
	sta $3da8,x
	ldy scratch_0
	rts
FASTFONT_H1_12
	lda TransposedFontRow0_0,y
	sta $2228,x
	lda TransposedFontRow0_1,y
	sta $2628,x
	lda TransposedFontRow0_2,y
	sta $2a28,x
	lda TransposedFontRow0_3,y
	sta $2e28,x
	lda TransposedFontRow0_4,y
	sta $3228,x
	lda TransposedFontRow0_5,y
	sta $3628,x
	lda TransposedFontRow0_6,y
	sta $3a28,x
	lda TransposedFontRow0_7,y
	sta $3e28,x
	ldy scratch_0
	rts
FASTFONT_H1_13
	lda TransposedFontRow0_0,y
	sta $22a8,x
	lda TransposedFontRow0_1,y
	sta $26a8,x
	lda TransposedFontRow0_2,y
	sta $2aa8,x
	lda TransposedFontRow0_3,y
	sta $2ea8,x
	lda TransposedFontRow0_4,y
	sta $32a8,x
	lda TransposedFontRow0_5,y
	sta $36a8,x
	lda TransposedFontRow0_6,y
	sta $3aa8,x
	lda TransposedFontRow0_7,y
	sta $3ea8,x
	ldy scratch_0
	rts
FASTFONT_H1_14
	lda TransposedFontRow0_0,y
	sta $2328,x
	lda TransposedFontRow0_1,y
	sta $2728,x
	lda TransposedFontRow0_2,y
	sta $2b28,x
	lda TransposedFontRow0_3,y
	sta $2f28,x
	lda TransposedFontRow0_4,y
	sta $3328,x
	lda TransposedFontRow0_5,y
	sta $3728,x
	lda TransposedFontRow0_6,y
	sta $3b28,x
	lda TransposedFontRow0_7,y
	sta $3f28,x
	ldy scratch_0
	rts
FASTFONT_H1_15
	lda TransposedFontRow0_0,y
	sta $23a8,x
	lda TransposedFontRow0_1,y
	sta $27a8,x
	lda TransposedFontRow0_2,y
	sta $2ba8,x
	lda TransposedFontRow0_3,y
	sta $2fa8,x
	lda TransposedFontRow0_4,y
	sta $33a8,x
	lda TransposedFontRow0_5,y
	sta $37a8,x
	lda TransposedFontRow0_6,y
	sta $3ba8,x
	lda TransposedFontRow0_7,y
	sta $3fa8,x
	ldy scratch_0
	rts
FASTFONT_H1_16
	lda TransposedFontRow0_0,y
	sta $2050,x
	lda TransposedFontRow0_1,y
	sta $2450,x
	lda TransposedFontRow0_2,y
	sta $2850,x
	lda TransposedFontRow0_3,y
	sta $2c50,x
	lda TransposedFontRow0_4,y
	sta $3050,x
	lda TransposedFontRow0_5,y
	sta $3450,x
	lda TransposedFontRow0_6,y
	sta $3850,x
	lda TransposedFontRow0_7,y
	sta $3c50,x
	ldy scratch_0
	rts
FASTFONT_H1_17
	lda TransposedFontRow0_0,y
	sta $20d0,x
	lda TransposedFontRow0_1,y
	sta $24d0,x
	lda TransposedFontRow0_2,y
	sta $28d0,x
	lda TransposedFontRow0_3,y
	sta $2cd0,x
	lda TransposedFontRow0_4,y
	sta $30d0,x
	lda TransposedFontRow0_5,y
	sta $34d0,x
	lda TransposedFontRow0_6,y
	sta $38d0,x
	lda TransposedFontRow0_7,y
	sta $3cd0,x
	ldy scratch_0
	rts
FASTFONT_H1_18
	lda TransposedFontRow0_0,y
	sta $2150,x
	lda TransposedFontRow0_1,y
	sta $2550,x
	lda TransposedFontRow0_2,y
	sta $2950,x
	lda TransposedFontRow0_3,y
	sta $2d50,x
	lda TransposedFontRow0_4,y
	sta $3150,x
	lda TransposedFontRow0_5,y
	sta $3550,x
	lda TransposedFontRow0_6,y
	sta $3950,x
	lda TransposedFontRow0_7,y
	sta $3d50,x
	ldy scratch_0
	rts
FASTFONT_H1_19
	lda TransposedFontRow0_0,y
	sta $21d0,x
	lda TransposedFontRow0_1,y
	sta $25d0,x
	lda TransposedFontRow0_2,y
	sta $29d0,x
	lda TransposedFontRow0_3,y
	sta $2dd0,x
	lda TransposedFontRow0_4,y
	sta $31d0,x
	lda TransposedFontRow0_5,y
	sta $35d0,x
	lda TransposedFontRow0_6,y
	sta $39d0,x
	lda TransposedFontRow0_7,y
	sta $3dd0,x
	ldy scratch_0
	rts
FASTFONT_H1_20
	lda TransposedFontRow0_0,y
	sta $2250,x
	lda TransposedFontRow0_1,y
	sta $2650,x
	lda TransposedFontRow0_2,y
	sta $2a50,x
	lda TransposedFontRow0_3,y
	sta $2e50,x
	lda TransposedFontRow0_4,y
	sta $3250,x
	lda TransposedFontRow0_5,y
	sta $3650,x
	lda TransposedFontRow0_6,y
	sta $3a50,x
	lda TransposedFontRow0_7,y
	sta $3e50,x
	ldy scratch_0
	rts
FASTFONT_H1_21
	lda TransposedFontRow0_0,y
	sta $22d0,x
	lda TransposedFontRow0_1,y
	sta $26d0,x
	lda TransposedFontRow0_2,y
	sta $2ad0,x
	lda TransposedFontRow0_3,y
	sta $2ed0,x
	lda TransposedFontRow0_4,y
	sta $32d0,x
	lda TransposedFontRow0_5,y
	sta $36d0,x
	lda TransposedFontRow0_6,y
	sta $3ad0,x
	lda TransposedFontRow0_7,y
	sta $3ed0,x
	ldy scratch_0
	rts
FASTFONT_H1_22
	lda TransposedFontRow0_0,y
	sta $2350,x
	lda TransposedFontRow0_1,y
	sta $2750,x
	lda TransposedFontRow0_2,y
	sta $2b50,x
	lda TransposedFontRow0_3,y
	sta $2f50,x
	lda TransposedFontRow0_4,y
	sta $3350,x
	lda TransposedFontRow0_5,y
	sta $3750,x
	lda TransposedFontRow0_6,y
	sta $3b50,x
	lda TransposedFontRow0_7,y
	sta $3f50,x
	ldy scratch_0
	rts
FASTFONT_H1_23
	lda TransposedFontRow0_0,y
	sta $23d0,x
	lda TransposedFontRow0_1,y
	sta $27d0,x
	lda TransposedFontRow0_2,y
	sta $2bd0,x
	lda TransposedFontRow0_3,y
	sta $2fd0,x
	lda TransposedFontRow0_4,y
	sta $33d0,x
	lda TransposedFontRow0_5,y
	sta $37d0,x
	lda TransposedFontRow0_6,y
	sta $3bd0,x
	lda TransposedFontRow0_7,y
	sta $3fd0,x
	ldy scratch_0
	rts

TransposedFontRow0_0
	.byte $00, $00, $00, $14, $00, $00, $14, $14, $00, $00, $14, $14, $00, $00, $14, $00
	.byte $00, $00, $00, $1c, $00, $00, $1c, $1c, $00, $00, $1c, $1c, $00, $00, $1c, $00
	.byte $80, $87, $b6, $aa, $d5, $b7, $86, $8c, $b8, $87, $98, $8c, $80, $80, $80, $e0
	.byte $9e, $8c, $9e, $9e, $b8, $bf, $9e, $bf, $9e, $9e, $80, $80, $f0, $80, $87, $9e
	.byte $9e, $9e, $9f, $9e, $9f, $bf, $bf, $9e, $b3, $bf, $b0, $b3, $83, $b3, $b3, $9e
	.byte $9f, $9e, $9f, $9e, $bf, $b3, $b3, $b3, $33, $b3, $bf, $bc, $83, $8f, $8c, $80
	.byte $86, $80, $83, $80, $b0, $80, $9c, $80, $83, $80, $b0, $83, $8e, $80, $80, $80
	.byte $80, $80, $80, $80, $86, $80, $80, $80, $80, $80, $80, $9c, $8c, $8e, $86, $00
TransposedFontRow0_1
	.byte $00, $00, $00, $14, $00, $00, $14, $14, $00, $00, $14, $14, $00, $00, $14, $00
	.byte $00, $00, $00, $1c, $00, $00, $1c, $1c, $00, $00, $1c, $1c, $00, $00, $1c, $00
	.byte $80, $87, $b6, $aa, $d5, $b7, $8f, $8c, $9c, $8e, $8e, $8c, $80, $80, $80, $f0
	.byte $bf, $8e, $bf, $bf, $bc, $bf, $bf, $bf, $bf, $bf, $9c, $87, $b8, $80, $8e, $bf
	.byte $b3, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $b3, $bf, $b0, $bb, $83, $bf, $b3, $bf
	.byte $bf, $bf, $bf, $bf, $bf, $b3, $b3, $b3, $9b, $b3, $bf, $bc, $87, $8f, $9e, $80
	.byte $8c, $80, $83, $80, $b0, $80, $b6, $80, $83, $8c, $80, $83, $8c, $80, $80, $80
	.byte $80, $80, $80, $80, $86, $80, $80, $80, $80, $80, $80, $9e, $8c, $9e, $bf, $00
TransposedFontRow0_2
	.byte $00, $00, $00, $14, $00, $00, $14, $14, $00, $00, $14, $14, $00, $00, $14, $00
	.byte $00, $00, $00, $1c, $00, $00, $1c, $1c, $00, $00, $1c, $1c, $00, $00, $1c, $00
	.byte $80, $87, $a4, $aa, $d5, $98, $86, $88, $8e, $9c, $bf, $bf, $80, $be, $80, $b8
	.byte $b3, $8f, $b3, $b0, $b6, $83, $83, $b0, $b3, $b3, $9c, $87, $9c, $be, $9c, $b3
	.byte $b3, $b3, $b3, $b3, $b3, $83, $83, $83, $b3, $8c, $b0, $9f, $83, $b3, $b7, $b3
	.byte $b3, $a3, $b3, $87, $8c, $b3, $b3, $b3, $1e, $b3, $98, $8c, $8e, $8c, $bf, $80
	.byte $98, $9e, $9f, $9e, $be, $9e, $86, $9e, $9f, $80, $b0, $b3, $8c, $b3, $9f, $9e
	.byte $9f, $be, $9f, $9e, $9f, $b3, $b3, $b3, $b3, $b3, $bf, $86, $8c, $98, $98, $00
TransposedFontRow0_3
	.byte $00, $00, $00, $14, $00, $54, $54, $54, $00, $15, $15, $15, $55, $55, $55, $2a
	.byte $00, $00, $00, $1c, $00, $7c, $7c, $7c, $00, $1f, $1f, $1f, $7f, $7f, $7f, $00
	.byte $80, $87, $b6, $aa, $d5, $8c, $8f, $8c, $8e, $9c, $9f, $bf, $80, $be, $80, $9c
	.byte $b3, $8c, $38, $be, $b3, $9f, $9f, $98, $9e, $be, $80, $80, $8e, $80, $b8, $98
	.byte $bb, $bf, $9f, $83, $b3, $9f, $9f, $bb, $bf, $8c, $b0, $8f, $83, $b3, $bf, $b3
	.byte $bf, $a3, $bf, $9e, $8c, $b3, $b3, $b3, $8e, $9e, $8c, $8c, $9c, $8c, $80, $80
	.byte $80, $b0, $b3, $b3, $b3, $b3, $9f, $b3, $b3, $8c, $b0, $9b, $8c, $bf, $b3, $b3
	.byte $b3, $b3, $b3, $83, $86, $b3, $b3, $b3, $9e, $b3, $98, $87, $8c, $b8, $80, $00
TransposedFontRow0_4
	.byte $00, $00, $00, $14, $00, $54, $54, $54, $00, $15, $15, $15, $55, $55, $55, $2a
	.byte $00, $00, $00, $1c, $00, $7c, $7c, $7c, $00, $1f, $1f, $1f, $7f, $7f, $7f, $00
	.byte $80, $80, $80, $aa, $d5, $86, $bb, $80, $8e, $9c, $9f, $8c, $80, $80, $80, $8e
	.byte $b3, $8c, $8e, $b0, $bf, $b0, $b3, $8c, $b3, $b0, $80, $80, $9c, $be, $9c, $8c
	.byte $bb, $bf, $b3, $b3, $b3, $83, $9f, $b3, $bf, $8c, $b3, $9f, $83, $b3, $bb, $b3
	.byte $9f, $ab, $9f, $b8, $8c, $b3, $b3, $b3, $1e, $8c, $86, $8c, $b8, $8c, $80, $80
	.byte $80, $be, $b3, $83, $b3, $9f, $86, $b3, $b3, $8c, $b0, $8f, $8c, $b3, $b3, $b3
	.byte $b3, $b3, $83, $9e, $86, $b3, $b3, $b3, $8c, $b3, $8c, $86, $8c, $98, $80, $00
TransposedFontRow0_5
	.byte $00, $00, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $00
	.byte $00, $00, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $00
	.byte $80, $87, $80, $aa, $d5, $bb, $9b, $80, $9c, $8e, $bf, $8c, $87, $80, $87, $87
	.byte $bf, $bf, $bf, $bf, $b0, $bf, $bf, $8c, $bf, $bf, $9c, $87, $b8, $80, $8e, $80
	.byte $83, $b3, $bf, $bf, $bf, $bf, $83, $bf, $b3, $bf, $bf, $bb, $bf, $b3, $b3, $bf
	.byte $83, $93, $bb, $bf, $8c, $bf, $9e, $bf, $9b, $8c, $bf, $bc, $f0, $8f, $80, $ff
	.byte $80, $b3, $b3, $b3, $b3, $83, $86, $be, $b3, $8c, $b3, $9b, $8c, $b3, $b3, $b3
	.byte $9f, $be, $83, $b0, $b6, $b3, $9e, $bf, $9e, $be, $86, $9e, $8c, $9e, $80, $00
TransposedFontRow0_6
	.byte $00, $00, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $00
	.byte $00, $00, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $00
	.byte $80, $87, $80, $aa, $d5, $bb, $ae, $80, $b8, $87, $9e, $80, $86, $80, $87, $83
	.byte $9e, $bf, $bf, $9e, $b0, $9e, $9e, $8c, $9e, $9e, $9c, $86, $f0, $80, $87, $8c
	.byte $be, $b3, $9f, $9e, $9f, $bf, $83, $9e, $b3, $bf, $9e, $b3, $bf, $b3, $b3, $9e
	.byte $83, $ae, $b3, $9e, $8c, $9e, $8c, $b3, $33, $8c, $bf, $bc, $e0, $8f, $80, $ff
	.byte $80, $be, $9f, $9e, $be, $9e, $86, $b0, $b3, $8c, $b3, $b3, $9e, $b3, $b3, $9e
	.byte $83, $b0, $83, $9e, $9c, $be, $8c, $b3, $b3, $b0, $bf, $9c, $8c, $8e, $80, $00
TransposedFontRow0_7
	.byte $00, $00, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $00
	.byte $00, $00, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $00
	.byte $80, $80, $80, $aa, $d5, $80, $80, $80, $80, $80, $80, $80, $83, $80, $80, $80
	.byte $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $83, $80, $80, $80, $80
	.byte $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80
	.byte $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80
	.byte $80, $80, $80, $80, $80, $80, $80, $9e, $80, $80, $9e, $80, $80, $80, $80, $80
	.byte $83, $b0, $80, $80, $80, $80, $80, $80, $80, $9e, $80, $80, $8c, $80, $80, $00

