; AUTOGENERATED FILE; DO NOT EDIT!
;
; This file was generated by asmgen.py, a 6502 code generator sponsored by
; the Player/Missile Podcast. (The sprite compiler is based on HiSprite by
; Quinn Dunki).
;
; The code produced by asmgen is licensed under the Creative Commons
; Attribution 4.0 International (CC BY 4.0), so you are free to use the code in
; this file for any purpose. (The code generator itself is licensed under the
; GPLv3.)

FASTFONT_H1	; A = character, X = column, Y = row; A is clobbered, X&Y are not
	pha
	lda FASTFONT_H1_JMP_HI,y
	sta FASTFONT_H1_JMP+2
	lda FASTFONT_H1_JMP_LO,y
	sta FASTFONT_H1_JMP+1
	sty scratch_0
	pla
	tay
FASTFONT_H1_JMP
	jmp $ffff


FASTFONT_H1_JMP_HI
	.byte >FASTFONT_H1_0
	.byte >FASTFONT_H1_1
	.byte >FASTFONT_H1_2
	.byte >FASTFONT_H1_3
	.byte >FASTFONT_H1_4
	.byte >FASTFONT_H1_5
FASTFONT_H1_JMP_LO
	.byte <FASTFONT_H1_0
	.byte <FASTFONT_H1_1
	.byte <FASTFONT_H1_2
	.byte <FASTFONT_H1_3
	.byte <FASTFONT_H1_4
	.byte <FASTFONT_H1_5

FASTFONT_H1_0
	lda TransposedFontRow0_0,y
	sta $2000,x
	lda TransposedFontRow0_1,y
	sta $2400,x
	lda TransposedFontRow0_2,y
	sta $2800,x
	lda TransposedFontRow0_3,y
	sta $2c00,x
	lda TransposedFontRow0_4,y
	sta $3000,x
	lda TransposedFontRow0_5,y
	sta $3400,x
	lda TransposedFontRow0_6,y
	sta $3800,x
	lda TransposedFontRow0_7,y
	sta $3c00,x
	lda TransposedFontRow0_8,y
	sta $2080,x
	lda TransposedFontRow0_9,y
	sta $2480,x
	lda TransposedFontRow0_10,y
	sta $2880,x
	lda TransposedFontRow0_11,y
	sta $2c80,x
	lda TransposedFontRow0_12,y
	sta $3080,x
	lda TransposedFontRow0_13,y
	sta $3480,x
	lda TransposedFontRow0_14,y
	sta $3880,x
	lda TransposedFontRow0_15,y
	sta $3c80,x
	lda TransposedFontRow0_16,y
	sta $2100,x
	lda TransposedFontRow0_17,y
	sta $2500,x
	lda TransposedFontRow0_18,y
	sta $2900,x
	lda TransposedFontRow0_19,y
	sta $2d00,x
	lda TransposedFontRow0_20,y
	sta $3100,x
	lda TransposedFontRow0_21,y
	sta $3500,x
	lda TransposedFontRow0_22,y
	sta $3900,x
	lda TransposedFontRow0_23,y
	sta $3d00,x
	lda TransposedFontRow0_24,y
	sta $2180,x
	lda TransposedFontRow0_25,y
	sta $2580,x
	lda TransposedFontRow0_26,y
	sta $2980,x
	lda TransposedFontRow0_27,y
	sta $2d80,x
	lda TransposedFontRow0_28,y
	sta $3180,x
	lda TransposedFontRow0_29,y
	sta $3580,x
	lda TransposedFontRow0_30,y
	sta $3980,x
	lda TransposedFontRow0_31,y
	sta $3d80,x
	lda TransposedFontRow1_0,y
	sta $2001,x
	lda TransposedFontRow1_1,y
	sta $2401,x
	lda TransposedFontRow1_2,y
	sta $2801,x
	lda TransposedFontRow1_3,y
	sta $2c01,x
	lda TransposedFontRow1_4,y
	sta $3001,x
	lda TransposedFontRow1_5,y
	sta $3401,x
	lda TransposedFontRow1_6,y
	sta $3801,x
	lda TransposedFontRow1_7,y
	sta $3c01,x
	lda TransposedFontRow1_8,y
	sta $2081,x
	lda TransposedFontRow1_9,y
	sta $2481,x
	lda TransposedFontRow1_10,y
	sta $2881,x
	lda TransposedFontRow1_11,y
	sta $2c81,x
	lda TransposedFontRow1_12,y
	sta $3081,x
	lda TransposedFontRow1_13,y
	sta $3481,x
	lda TransposedFontRow1_14,y
	sta $3881,x
	lda TransposedFontRow1_15,y
	sta $3c81,x
	lda TransposedFontRow1_16,y
	sta $2101,x
	lda TransposedFontRow1_17,y
	sta $2501,x
	lda TransposedFontRow1_18,y
	sta $2901,x
	lda TransposedFontRow1_19,y
	sta $2d01,x
	lda TransposedFontRow1_20,y
	sta $3101,x
	lda TransposedFontRow1_21,y
	sta $3501,x
	lda TransposedFontRow1_22,y
	sta $3901,x
	lda TransposedFontRow1_23,y
	sta $3d01,x
	lda TransposedFontRow1_24,y
	sta $2181,x
	lda TransposedFontRow1_25,y
	sta $2581,x
	lda TransposedFontRow1_26,y
	sta $2981,x
	lda TransposedFontRow1_27,y
	sta $2d81,x
	lda TransposedFontRow1_28,y
	sta $3181,x
	lda TransposedFontRow1_29,y
	sta $3581,x
	lda TransposedFontRow1_30,y
	sta $3981,x
	lda TransposedFontRow1_31,y
	sta $3d81,x
	lda TransposedFontRow2_0,y
	sta $2002,x
	lda TransposedFontRow2_1,y
	sta $2402,x
	lda TransposedFontRow2_2,y
	sta $2802,x
	lda TransposedFontRow2_3,y
	sta $2c02,x
	lda TransposedFontRow2_4,y
	sta $3002,x
	lda TransposedFontRow2_5,y
	sta $3402,x
	lda TransposedFontRow2_6,y
	sta $3802,x
	lda TransposedFontRow2_7,y
	sta $3c02,x
	lda TransposedFontRow2_8,y
	sta $2082,x
	lda TransposedFontRow2_9,y
	sta $2482,x
	lda TransposedFontRow2_10,y
	sta $2882,x
	lda TransposedFontRow2_11,y
	sta $2c82,x
	lda TransposedFontRow2_12,y
	sta $3082,x
	lda TransposedFontRow2_13,y
	sta $3482,x
	lda TransposedFontRow2_14,y
	sta $3882,x
	lda TransposedFontRow2_15,y
	sta $3c82,x
	lda TransposedFontRow2_16,y
	sta $2102,x
	lda TransposedFontRow2_17,y
	sta $2502,x
	lda TransposedFontRow2_18,y
	sta $2902,x
	lda TransposedFontRow2_19,y
	sta $2d02,x
	lda TransposedFontRow2_20,y
	sta $3102,x
	lda TransposedFontRow2_21,y
	sta $3502,x
	lda TransposedFontRow2_22,y
	sta $3902,x
	lda TransposedFontRow2_23,y
	sta $3d02,x
	lda TransposedFontRow2_24,y
	sta $2182,x
	lda TransposedFontRow2_25,y
	sta $2582,x
	lda TransposedFontRow2_26,y
	sta $2982,x
	lda TransposedFontRow2_27,y
	sta $2d82,x
	lda TransposedFontRow2_28,y
	sta $3182,x
	lda TransposedFontRow2_29,y
	sta $3582,x
	lda TransposedFontRow2_30,y
	sta $3982,x
	lda TransposedFontRow2_31,y
	sta $3d82,x
	lda TransposedFontRow3_0,y
	sta $2003,x
	lda TransposedFontRow3_1,y
	sta $2403,x
	lda TransposedFontRow3_2,y
	sta $2803,x
	lda TransposedFontRow3_3,y
	sta $2c03,x
	lda TransposedFontRow3_4,y
	sta $3003,x
	lda TransposedFontRow3_5,y
	sta $3403,x
	lda TransposedFontRow3_6,y
	sta $3803,x
	lda TransposedFontRow3_7,y
	sta $3c03,x
	lda TransposedFontRow3_8,y
	sta $2083,x
	lda TransposedFontRow3_9,y
	sta $2483,x
	lda TransposedFontRow3_10,y
	sta $2883,x
	lda TransposedFontRow3_11,y
	sta $2c83,x
	lda TransposedFontRow3_12,y
	sta $3083,x
	lda TransposedFontRow3_13,y
	sta $3483,x
	lda TransposedFontRow3_14,y
	sta $3883,x
	lda TransposedFontRow3_15,y
	sta $3c83,x
	lda TransposedFontRow3_16,y
	sta $2103,x
	lda TransposedFontRow3_17,y
	sta $2503,x
	lda TransposedFontRow3_18,y
	sta $2903,x
	lda TransposedFontRow3_19,y
	sta $2d03,x
	lda TransposedFontRow3_20,y
	sta $3103,x
	lda TransposedFontRow3_21,y
	sta $3503,x
	lda TransposedFontRow3_22,y
	sta $3903,x
	lda TransposedFontRow3_23,y
	sta $3d03,x
	lda TransposedFontRow3_24,y
	sta $2183,x
	lda TransposedFontRow3_25,y
	sta $2583,x
	lda TransposedFontRow3_26,y
	sta $2983,x
	lda TransposedFontRow3_27,y
	sta $2d83,x
	lda TransposedFontRow3_28,y
	sta $3183,x
	lda TransposedFontRow3_29,y
	sta $3583,x
	lda TransposedFontRow3_30,y
	sta $3983,x
	lda TransposedFontRow3_31,y
	sta $3d83,x
	ldy scratch_0
	rts
FASTFONT_H1_1
	lda TransposedFontRow0_0,y
	sta $2200,x
	lda TransposedFontRow0_1,y
	sta $2600,x
	lda TransposedFontRow0_2,y
	sta $2a00,x
	lda TransposedFontRow0_3,y
	sta $2e00,x
	lda TransposedFontRow0_4,y
	sta $3200,x
	lda TransposedFontRow0_5,y
	sta $3600,x
	lda TransposedFontRow0_6,y
	sta $3a00,x
	lda TransposedFontRow0_7,y
	sta $3e00,x
	lda TransposedFontRow0_8,y
	sta $2280,x
	lda TransposedFontRow0_9,y
	sta $2680,x
	lda TransposedFontRow0_10,y
	sta $2a80,x
	lda TransposedFontRow0_11,y
	sta $2e80,x
	lda TransposedFontRow0_12,y
	sta $3280,x
	lda TransposedFontRow0_13,y
	sta $3680,x
	lda TransposedFontRow0_14,y
	sta $3a80,x
	lda TransposedFontRow0_15,y
	sta $3e80,x
	lda TransposedFontRow0_16,y
	sta $2300,x
	lda TransposedFontRow0_17,y
	sta $2700,x
	lda TransposedFontRow0_18,y
	sta $2b00,x
	lda TransposedFontRow0_19,y
	sta $2f00,x
	lda TransposedFontRow0_20,y
	sta $3300,x
	lda TransposedFontRow0_21,y
	sta $3700,x
	lda TransposedFontRow0_22,y
	sta $3b00,x
	lda TransposedFontRow0_23,y
	sta $3f00,x
	lda TransposedFontRow0_24,y
	sta $2380,x
	lda TransposedFontRow0_25,y
	sta $2780,x
	lda TransposedFontRow0_26,y
	sta $2b80,x
	lda TransposedFontRow0_27,y
	sta $2f80,x
	lda TransposedFontRow0_28,y
	sta $3380,x
	lda TransposedFontRow0_29,y
	sta $3780,x
	lda TransposedFontRow0_30,y
	sta $3b80,x
	lda TransposedFontRow0_31,y
	sta $3f80,x
	lda TransposedFontRow1_0,y
	sta $2201,x
	lda TransposedFontRow1_1,y
	sta $2601,x
	lda TransposedFontRow1_2,y
	sta $2a01,x
	lda TransposedFontRow1_3,y
	sta $2e01,x
	lda TransposedFontRow1_4,y
	sta $3201,x
	lda TransposedFontRow1_5,y
	sta $3601,x
	lda TransposedFontRow1_6,y
	sta $3a01,x
	lda TransposedFontRow1_7,y
	sta $3e01,x
	lda TransposedFontRow1_8,y
	sta $2281,x
	lda TransposedFontRow1_9,y
	sta $2681,x
	lda TransposedFontRow1_10,y
	sta $2a81,x
	lda TransposedFontRow1_11,y
	sta $2e81,x
	lda TransposedFontRow1_12,y
	sta $3281,x
	lda TransposedFontRow1_13,y
	sta $3681,x
	lda TransposedFontRow1_14,y
	sta $3a81,x
	lda TransposedFontRow1_15,y
	sta $3e81,x
	lda TransposedFontRow1_16,y
	sta $2301,x
	lda TransposedFontRow1_17,y
	sta $2701,x
	lda TransposedFontRow1_18,y
	sta $2b01,x
	lda TransposedFontRow1_19,y
	sta $2f01,x
	lda TransposedFontRow1_20,y
	sta $3301,x
	lda TransposedFontRow1_21,y
	sta $3701,x
	lda TransposedFontRow1_22,y
	sta $3b01,x
	lda TransposedFontRow1_23,y
	sta $3f01,x
	lda TransposedFontRow1_24,y
	sta $2381,x
	lda TransposedFontRow1_25,y
	sta $2781,x
	lda TransposedFontRow1_26,y
	sta $2b81,x
	lda TransposedFontRow1_27,y
	sta $2f81,x
	lda TransposedFontRow1_28,y
	sta $3381,x
	lda TransposedFontRow1_29,y
	sta $3781,x
	lda TransposedFontRow1_30,y
	sta $3b81,x
	lda TransposedFontRow1_31,y
	sta $3f81,x
	lda TransposedFontRow2_0,y
	sta $2202,x
	lda TransposedFontRow2_1,y
	sta $2602,x
	lda TransposedFontRow2_2,y
	sta $2a02,x
	lda TransposedFontRow2_3,y
	sta $2e02,x
	lda TransposedFontRow2_4,y
	sta $3202,x
	lda TransposedFontRow2_5,y
	sta $3602,x
	lda TransposedFontRow2_6,y
	sta $3a02,x
	lda TransposedFontRow2_7,y
	sta $3e02,x
	lda TransposedFontRow2_8,y
	sta $2282,x
	lda TransposedFontRow2_9,y
	sta $2682,x
	lda TransposedFontRow2_10,y
	sta $2a82,x
	lda TransposedFontRow2_11,y
	sta $2e82,x
	lda TransposedFontRow2_12,y
	sta $3282,x
	lda TransposedFontRow2_13,y
	sta $3682,x
	lda TransposedFontRow2_14,y
	sta $3a82,x
	lda TransposedFontRow2_15,y
	sta $3e82,x
	lda TransposedFontRow2_16,y
	sta $2302,x
	lda TransposedFontRow2_17,y
	sta $2702,x
	lda TransposedFontRow2_18,y
	sta $2b02,x
	lda TransposedFontRow2_19,y
	sta $2f02,x
	lda TransposedFontRow2_20,y
	sta $3302,x
	lda TransposedFontRow2_21,y
	sta $3702,x
	lda TransposedFontRow2_22,y
	sta $3b02,x
	lda TransposedFontRow2_23,y
	sta $3f02,x
	lda TransposedFontRow2_24,y
	sta $2382,x
	lda TransposedFontRow2_25,y
	sta $2782,x
	lda TransposedFontRow2_26,y
	sta $2b82,x
	lda TransposedFontRow2_27,y
	sta $2f82,x
	lda TransposedFontRow2_28,y
	sta $3382,x
	lda TransposedFontRow2_29,y
	sta $3782,x
	lda TransposedFontRow2_30,y
	sta $3b82,x
	lda TransposedFontRow2_31,y
	sta $3f82,x
	lda TransposedFontRow3_0,y
	sta $2203,x
	lda TransposedFontRow3_1,y
	sta $2603,x
	lda TransposedFontRow3_2,y
	sta $2a03,x
	lda TransposedFontRow3_3,y
	sta $2e03,x
	lda TransposedFontRow3_4,y
	sta $3203,x
	lda TransposedFontRow3_5,y
	sta $3603,x
	lda TransposedFontRow3_6,y
	sta $3a03,x
	lda TransposedFontRow3_7,y
	sta $3e03,x
	lda TransposedFontRow3_8,y
	sta $2283,x
	lda TransposedFontRow3_9,y
	sta $2683,x
	lda TransposedFontRow3_10,y
	sta $2a83,x
	lda TransposedFontRow3_11,y
	sta $2e83,x
	lda TransposedFontRow3_12,y
	sta $3283,x
	lda TransposedFontRow3_13,y
	sta $3683,x
	lda TransposedFontRow3_14,y
	sta $3a83,x
	lda TransposedFontRow3_15,y
	sta $3e83,x
	lda TransposedFontRow3_16,y
	sta $2303,x
	lda TransposedFontRow3_17,y
	sta $2703,x
	lda TransposedFontRow3_18,y
	sta $2b03,x
	lda TransposedFontRow3_19,y
	sta $2f03,x
	lda TransposedFontRow3_20,y
	sta $3303,x
	lda TransposedFontRow3_21,y
	sta $3703,x
	lda TransposedFontRow3_22,y
	sta $3b03,x
	lda TransposedFontRow3_23,y
	sta $3f03,x
	lda TransposedFontRow3_24,y
	sta $2383,x
	lda TransposedFontRow3_25,y
	sta $2783,x
	lda TransposedFontRow3_26,y
	sta $2b83,x
	lda TransposedFontRow3_27,y
	sta $2f83,x
	lda TransposedFontRow3_28,y
	sta $3383,x
	lda TransposedFontRow3_29,y
	sta $3783,x
	lda TransposedFontRow3_30,y
	sta $3b83,x
	lda TransposedFontRow3_31,y
	sta $3f83,x
	ldy scratch_0
	rts
FASTFONT_H1_2
	lda TransposedFontRow0_0,y
	sta $2028,x
	lda TransposedFontRow0_1,y
	sta $2428,x
	lda TransposedFontRow0_2,y
	sta $2828,x
	lda TransposedFontRow0_3,y
	sta $2c28,x
	lda TransposedFontRow0_4,y
	sta $3028,x
	lda TransposedFontRow0_5,y
	sta $3428,x
	lda TransposedFontRow0_6,y
	sta $3828,x
	lda TransposedFontRow0_7,y
	sta $3c28,x
	lda TransposedFontRow0_8,y
	sta $20a8,x
	lda TransposedFontRow0_9,y
	sta $24a8,x
	lda TransposedFontRow0_10,y
	sta $28a8,x
	lda TransposedFontRow0_11,y
	sta $2ca8,x
	lda TransposedFontRow0_12,y
	sta $30a8,x
	lda TransposedFontRow0_13,y
	sta $34a8,x
	lda TransposedFontRow0_14,y
	sta $38a8,x
	lda TransposedFontRow0_15,y
	sta $3ca8,x
	lda TransposedFontRow0_16,y
	sta $2128,x
	lda TransposedFontRow0_17,y
	sta $2528,x
	lda TransposedFontRow0_18,y
	sta $2928,x
	lda TransposedFontRow0_19,y
	sta $2d28,x
	lda TransposedFontRow0_20,y
	sta $3128,x
	lda TransposedFontRow0_21,y
	sta $3528,x
	lda TransposedFontRow0_22,y
	sta $3928,x
	lda TransposedFontRow0_23,y
	sta $3d28,x
	lda TransposedFontRow0_24,y
	sta $21a8,x
	lda TransposedFontRow0_25,y
	sta $25a8,x
	lda TransposedFontRow0_26,y
	sta $29a8,x
	lda TransposedFontRow0_27,y
	sta $2da8,x
	lda TransposedFontRow0_28,y
	sta $31a8,x
	lda TransposedFontRow0_29,y
	sta $35a8,x
	lda TransposedFontRow0_30,y
	sta $39a8,x
	lda TransposedFontRow0_31,y
	sta $3da8,x
	lda TransposedFontRow1_0,y
	sta $2029,x
	lda TransposedFontRow1_1,y
	sta $2429,x
	lda TransposedFontRow1_2,y
	sta $2829,x
	lda TransposedFontRow1_3,y
	sta $2c29,x
	lda TransposedFontRow1_4,y
	sta $3029,x
	lda TransposedFontRow1_5,y
	sta $3429,x
	lda TransposedFontRow1_6,y
	sta $3829,x
	lda TransposedFontRow1_7,y
	sta $3c29,x
	lda TransposedFontRow1_8,y
	sta $20a9,x
	lda TransposedFontRow1_9,y
	sta $24a9,x
	lda TransposedFontRow1_10,y
	sta $28a9,x
	lda TransposedFontRow1_11,y
	sta $2ca9,x
	lda TransposedFontRow1_12,y
	sta $30a9,x
	lda TransposedFontRow1_13,y
	sta $34a9,x
	lda TransposedFontRow1_14,y
	sta $38a9,x
	lda TransposedFontRow1_15,y
	sta $3ca9,x
	lda TransposedFontRow1_16,y
	sta $2129,x
	lda TransposedFontRow1_17,y
	sta $2529,x
	lda TransposedFontRow1_18,y
	sta $2929,x
	lda TransposedFontRow1_19,y
	sta $2d29,x
	lda TransposedFontRow1_20,y
	sta $3129,x
	lda TransposedFontRow1_21,y
	sta $3529,x
	lda TransposedFontRow1_22,y
	sta $3929,x
	lda TransposedFontRow1_23,y
	sta $3d29,x
	lda TransposedFontRow1_24,y
	sta $21a9,x
	lda TransposedFontRow1_25,y
	sta $25a9,x
	lda TransposedFontRow1_26,y
	sta $29a9,x
	lda TransposedFontRow1_27,y
	sta $2da9,x
	lda TransposedFontRow1_28,y
	sta $31a9,x
	lda TransposedFontRow1_29,y
	sta $35a9,x
	lda TransposedFontRow1_30,y
	sta $39a9,x
	lda TransposedFontRow1_31,y
	sta $3da9,x
	lda TransposedFontRow2_0,y
	sta $202a,x
	lda TransposedFontRow2_1,y
	sta $242a,x
	lda TransposedFontRow2_2,y
	sta $282a,x
	lda TransposedFontRow2_3,y
	sta $2c2a,x
	lda TransposedFontRow2_4,y
	sta $302a,x
	lda TransposedFontRow2_5,y
	sta $342a,x
	lda TransposedFontRow2_6,y
	sta $382a,x
	lda TransposedFontRow2_7,y
	sta $3c2a,x
	lda TransposedFontRow2_8,y
	sta $20aa,x
	lda TransposedFontRow2_9,y
	sta $24aa,x
	lda TransposedFontRow2_10,y
	sta $28aa,x
	lda TransposedFontRow2_11,y
	sta $2caa,x
	lda TransposedFontRow2_12,y
	sta $30aa,x
	lda TransposedFontRow2_13,y
	sta $34aa,x
	lda TransposedFontRow2_14,y
	sta $38aa,x
	lda TransposedFontRow2_15,y
	sta $3caa,x
	lda TransposedFontRow2_16,y
	sta $212a,x
	lda TransposedFontRow2_17,y
	sta $252a,x
	lda TransposedFontRow2_18,y
	sta $292a,x
	lda TransposedFontRow2_19,y
	sta $2d2a,x
	lda TransposedFontRow2_20,y
	sta $312a,x
	lda TransposedFontRow2_21,y
	sta $352a,x
	lda TransposedFontRow2_22,y
	sta $392a,x
	lda TransposedFontRow2_23,y
	sta $3d2a,x
	lda TransposedFontRow2_24,y
	sta $21aa,x
	lda TransposedFontRow2_25,y
	sta $25aa,x
	lda TransposedFontRow2_26,y
	sta $29aa,x
	lda TransposedFontRow2_27,y
	sta $2daa,x
	lda TransposedFontRow2_28,y
	sta $31aa,x
	lda TransposedFontRow2_29,y
	sta $35aa,x
	lda TransposedFontRow2_30,y
	sta $39aa,x
	lda TransposedFontRow2_31,y
	sta $3daa,x
	lda TransposedFontRow3_0,y
	sta $202b,x
	lda TransposedFontRow3_1,y
	sta $242b,x
	lda TransposedFontRow3_2,y
	sta $282b,x
	lda TransposedFontRow3_3,y
	sta $2c2b,x
	lda TransposedFontRow3_4,y
	sta $302b,x
	lda TransposedFontRow3_5,y
	sta $342b,x
	lda TransposedFontRow3_6,y
	sta $382b,x
	lda TransposedFontRow3_7,y
	sta $3c2b,x
	lda TransposedFontRow3_8,y
	sta $20ab,x
	lda TransposedFontRow3_9,y
	sta $24ab,x
	lda TransposedFontRow3_10,y
	sta $28ab,x
	lda TransposedFontRow3_11,y
	sta $2cab,x
	lda TransposedFontRow3_12,y
	sta $30ab,x
	lda TransposedFontRow3_13,y
	sta $34ab,x
	lda TransposedFontRow3_14,y
	sta $38ab,x
	lda TransposedFontRow3_15,y
	sta $3cab,x
	lda TransposedFontRow3_16,y
	sta $212b,x
	lda TransposedFontRow3_17,y
	sta $252b,x
	lda TransposedFontRow3_18,y
	sta $292b,x
	lda TransposedFontRow3_19,y
	sta $2d2b,x
	lda TransposedFontRow3_20,y
	sta $312b,x
	lda TransposedFontRow3_21,y
	sta $352b,x
	lda TransposedFontRow3_22,y
	sta $392b,x
	lda TransposedFontRow3_23,y
	sta $3d2b,x
	lda TransposedFontRow3_24,y
	sta $21ab,x
	lda TransposedFontRow3_25,y
	sta $25ab,x
	lda TransposedFontRow3_26,y
	sta $29ab,x
	lda TransposedFontRow3_27,y
	sta $2dab,x
	lda TransposedFontRow3_28,y
	sta $31ab,x
	lda TransposedFontRow3_29,y
	sta $35ab,x
	lda TransposedFontRow3_30,y
	sta $39ab,x
	lda TransposedFontRow3_31,y
	sta $3dab,x
	ldy scratch_0
	rts
FASTFONT_H1_3
	lda TransposedFontRow0_0,y
	sta $2228,x
	lda TransposedFontRow0_1,y
	sta $2628,x
	lda TransposedFontRow0_2,y
	sta $2a28,x
	lda TransposedFontRow0_3,y
	sta $2e28,x
	lda TransposedFontRow0_4,y
	sta $3228,x
	lda TransposedFontRow0_5,y
	sta $3628,x
	lda TransposedFontRow0_6,y
	sta $3a28,x
	lda TransposedFontRow0_7,y
	sta $3e28,x
	lda TransposedFontRow0_8,y
	sta $22a8,x
	lda TransposedFontRow0_9,y
	sta $26a8,x
	lda TransposedFontRow0_10,y
	sta $2aa8,x
	lda TransposedFontRow0_11,y
	sta $2ea8,x
	lda TransposedFontRow0_12,y
	sta $32a8,x
	lda TransposedFontRow0_13,y
	sta $36a8,x
	lda TransposedFontRow0_14,y
	sta $3aa8,x
	lda TransposedFontRow0_15,y
	sta $3ea8,x
	lda TransposedFontRow0_16,y
	sta $2328,x
	lda TransposedFontRow0_17,y
	sta $2728,x
	lda TransposedFontRow0_18,y
	sta $2b28,x
	lda TransposedFontRow0_19,y
	sta $2f28,x
	lda TransposedFontRow0_20,y
	sta $3328,x
	lda TransposedFontRow0_21,y
	sta $3728,x
	lda TransposedFontRow0_22,y
	sta $3b28,x
	lda TransposedFontRow0_23,y
	sta $3f28,x
	lda TransposedFontRow0_24,y
	sta $23a8,x
	lda TransposedFontRow0_25,y
	sta $27a8,x
	lda TransposedFontRow0_26,y
	sta $2ba8,x
	lda TransposedFontRow0_27,y
	sta $2fa8,x
	lda TransposedFontRow0_28,y
	sta $33a8,x
	lda TransposedFontRow0_29,y
	sta $37a8,x
	lda TransposedFontRow0_30,y
	sta $3ba8,x
	lda TransposedFontRow0_31,y
	sta $3fa8,x
	lda TransposedFontRow1_0,y
	sta $2229,x
	lda TransposedFontRow1_1,y
	sta $2629,x
	lda TransposedFontRow1_2,y
	sta $2a29,x
	lda TransposedFontRow1_3,y
	sta $2e29,x
	lda TransposedFontRow1_4,y
	sta $3229,x
	lda TransposedFontRow1_5,y
	sta $3629,x
	lda TransposedFontRow1_6,y
	sta $3a29,x
	lda TransposedFontRow1_7,y
	sta $3e29,x
	lda TransposedFontRow1_8,y
	sta $22a9,x
	lda TransposedFontRow1_9,y
	sta $26a9,x
	lda TransposedFontRow1_10,y
	sta $2aa9,x
	lda TransposedFontRow1_11,y
	sta $2ea9,x
	lda TransposedFontRow1_12,y
	sta $32a9,x
	lda TransposedFontRow1_13,y
	sta $36a9,x
	lda TransposedFontRow1_14,y
	sta $3aa9,x
	lda TransposedFontRow1_15,y
	sta $3ea9,x
	lda TransposedFontRow1_16,y
	sta $2329,x
	lda TransposedFontRow1_17,y
	sta $2729,x
	lda TransposedFontRow1_18,y
	sta $2b29,x
	lda TransposedFontRow1_19,y
	sta $2f29,x
	lda TransposedFontRow1_20,y
	sta $3329,x
	lda TransposedFontRow1_21,y
	sta $3729,x
	lda TransposedFontRow1_22,y
	sta $3b29,x
	lda TransposedFontRow1_23,y
	sta $3f29,x
	lda TransposedFontRow1_24,y
	sta $23a9,x
	lda TransposedFontRow1_25,y
	sta $27a9,x
	lda TransposedFontRow1_26,y
	sta $2ba9,x
	lda TransposedFontRow1_27,y
	sta $2fa9,x
	lda TransposedFontRow1_28,y
	sta $33a9,x
	lda TransposedFontRow1_29,y
	sta $37a9,x
	lda TransposedFontRow1_30,y
	sta $3ba9,x
	lda TransposedFontRow1_31,y
	sta $3fa9,x
	lda TransposedFontRow2_0,y
	sta $222a,x
	lda TransposedFontRow2_1,y
	sta $262a,x
	lda TransposedFontRow2_2,y
	sta $2a2a,x
	lda TransposedFontRow2_3,y
	sta $2e2a,x
	lda TransposedFontRow2_4,y
	sta $322a,x
	lda TransposedFontRow2_5,y
	sta $362a,x
	lda TransposedFontRow2_6,y
	sta $3a2a,x
	lda TransposedFontRow2_7,y
	sta $3e2a,x
	lda TransposedFontRow2_8,y
	sta $22aa,x
	lda TransposedFontRow2_9,y
	sta $26aa,x
	lda TransposedFontRow2_10,y
	sta $2aaa,x
	lda TransposedFontRow2_11,y
	sta $2eaa,x
	lda TransposedFontRow2_12,y
	sta $32aa,x
	lda TransposedFontRow2_13,y
	sta $36aa,x
	lda TransposedFontRow2_14,y
	sta $3aaa,x
	lda TransposedFontRow2_15,y
	sta $3eaa,x
	lda TransposedFontRow2_16,y
	sta $232a,x
	lda TransposedFontRow2_17,y
	sta $272a,x
	lda TransposedFontRow2_18,y
	sta $2b2a,x
	lda TransposedFontRow2_19,y
	sta $2f2a,x
	lda TransposedFontRow2_20,y
	sta $332a,x
	lda TransposedFontRow2_21,y
	sta $372a,x
	lda TransposedFontRow2_22,y
	sta $3b2a,x
	lda TransposedFontRow2_23,y
	sta $3f2a,x
	lda TransposedFontRow2_24,y
	sta $23aa,x
	lda TransposedFontRow2_25,y
	sta $27aa,x
	lda TransposedFontRow2_26,y
	sta $2baa,x
	lda TransposedFontRow2_27,y
	sta $2faa,x
	lda TransposedFontRow2_28,y
	sta $33aa,x
	lda TransposedFontRow2_29,y
	sta $37aa,x
	lda TransposedFontRow2_30,y
	sta $3baa,x
	lda TransposedFontRow2_31,y
	sta $3faa,x
	lda TransposedFontRow3_0,y
	sta $222b,x
	lda TransposedFontRow3_1,y
	sta $262b,x
	lda TransposedFontRow3_2,y
	sta $2a2b,x
	lda TransposedFontRow3_3,y
	sta $2e2b,x
	lda TransposedFontRow3_4,y
	sta $322b,x
	lda TransposedFontRow3_5,y
	sta $362b,x
	lda TransposedFontRow3_6,y
	sta $3a2b,x
	lda TransposedFontRow3_7,y
	sta $3e2b,x
	lda TransposedFontRow3_8,y
	sta $22ab,x
	lda TransposedFontRow3_9,y
	sta $26ab,x
	lda TransposedFontRow3_10,y
	sta $2aab,x
	lda TransposedFontRow3_11,y
	sta $2eab,x
	lda TransposedFontRow3_12,y
	sta $32ab,x
	lda TransposedFontRow3_13,y
	sta $36ab,x
	lda TransposedFontRow3_14,y
	sta $3aab,x
	lda TransposedFontRow3_15,y
	sta $3eab,x
	lda TransposedFontRow3_16,y
	sta $232b,x
	lda TransposedFontRow3_17,y
	sta $272b,x
	lda TransposedFontRow3_18,y
	sta $2b2b,x
	lda TransposedFontRow3_19,y
	sta $2f2b,x
	lda TransposedFontRow3_20,y
	sta $332b,x
	lda TransposedFontRow3_21,y
	sta $372b,x
	lda TransposedFontRow3_22,y
	sta $3b2b,x
	lda TransposedFontRow3_23,y
	sta $3f2b,x
	lda TransposedFontRow3_24,y
	sta $23ab,x
	lda TransposedFontRow3_25,y
	sta $27ab,x
	lda TransposedFontRow3_26,y
	sta $2bab,x
	lda TransposedFontRow3_27,y
	sta $2fab,x
	lda TransposedFontRow3_28,y
	sta $33ab,x
	lda TransposedFontRow3_29,y
	sta $37ab,x
	lda TransposedFontRow3_30,y
	sta $3bab,x
	lda TransposedFontRow3_31,y
	sta $3fab,x
	ldy scratch_0
	rts
FASTFONT_H1_4
	lda TransposedFontRow0_0,y
	sta $2050,x
	lda TransposedFontRow0_1,y
	sta $2450,x
	lda TransposedFontRow0_2,y
	sta $2850,x
	lda TransposedFontRow0_3,y
	sta $2c50,x
	lda TransposedFontRow0_4,y
	sta $3050,x
	lda TransposedFontRow0_5,y
	sta $3450,x
	lda TransposedFontRow0_6,y
	sta $3850,x
	lda TransposedFontRow0_7,y
	sta $3c50,x
	lda TransposedFontRow0_8,y
	sta $20d0,x
	lda TransposedFontRow0_9,y
	sta $24d0,x
	lda TransposedFontRow0_10,y
	sta $28d0,x
	lda TransposedFontRow0_11,y
	sta $2cd0,x
	lda TransposedFontRow0_12,y
	sta $30d0,x
	lda TransposedFontRow0_13,y
	sta $34d0,x
	lda TransposedFontRow0_14,y
	sta $38d0,x
	lda TransposedFontRow0_15,y
	sta $3cd0,x
	lda TransposedFontRow0_16,y
	sta $2150,x
	lda TransposedFontRow0_17,y
	sta $2550,x
	lda TransposedFontRow0_18,y
	sta $2950,x
	lda TransposedFontRow0_19,y
	sta $2d50,x
	lda TransposedFontRow0_20,y
	sta $3150,x
	lda TransposedFontRow0_21,y
	sta $3550,x
	lda TransposedFontRow0_22,y
	sta $3950,x
	lda TransposedFontRow0_23,y
	sta $3d50,x
	lda TransposedFontRow0_24,y
	sta $21d0,x
	lda TransposedFontRow0_25,y
	sta $25d0,x
	lda TransposedFontRow0_26,y
	sta $29d0,x
	lda TransposedFontRow0_27,y
	sta $2dd0,x
	lda TransposedFontRow0_28,y
	sta $31d0,x
	lda TransposedFontRow0_29,y
	sta $35d0,x
	lda TransposedFontRow0_30,y
	sta $39d0,x
	lda TransposedFontRow0_31,y
	sta $3dd0,x
	lda TransposedFontRow1_0,y
	sta $2051,x
	lda TransposedFontRow1_1,y
	sta $2451,x
	lda TransposedFontRow1_2,y
	sta $2851,x
	lda TransposedFontRow1_3,y
	sta $2c51,x
	lda TransposedFontRow1_4,y
	sta $3051,x
	lda TransposedFontRow1_5,y
	sta $3451,x
	lda TransposedFontRow1_6,y
	sta $3851,x
	lda TransposedFontRow1_7,y
	sta $3c51,x
	lda TransposedFontRow1_8,y
	sta $20d1,x
	lda TransposedFontRow1_9,y
	sta $24d1,x
	lda TransposedFontRow1_10,y
	sta $28d1,x
	lda TransposedFontRow1_11,y
	sta $2cd1,x
	lda TransposedFontRow1_12,y
	sta $30d1,x
	lda TransposedFontRow1_13,y
	sta $34d1,x
	lda TransposedFontRow1_14,y
	sta $38d1,x
	lda TransposedFontRow1_15,y
	sta $3cd1,x
	lda TransposedFontRow1_16,y
	sta $2151,x
	lda TransposedFontRow1_17,y
	sta $2551,x
	lda TransposedFontRow1_18,y
	sta $2951,x
	lda TransposedFontRow1_19,y
	sta $2d51,x
	lda TransposedFontRow1_20,y
	sta $3151,x
	lda TransposedFontRow1_21,y
	sta $3551,x
	lda TransposedFontRow1_22,y
	sta $3951,x
	lda TransposedFontRow1_23,y
	sta $3d51,x
	lda TransposedFontRow1_24,y
	sta $21d1,x
	lda TransposedFontRow1_25,y
	sta $25d1,x
	lda TransposedFontRow1_26,y
	sta $29d1,x
	lda TransposedFontRow1_27,y
	sta $2dd1,x
	lda TransposedFontRow1_28,y
	sta $31d1,x
	lda TransposedFontRow1_29,y
	sta $35d1,x
	lda TransposedFontRow1_30,y
	sta $39d1,x
	lda TransposedFontRow1_31,y
	sta $3dd1,x
	lda TransposedFontRow2_0,y
	sta $2052,x
	lda TransposedFontRow2_1,y
	sta $2452,x
	lda TransposedFontRow2_2,y
	sta $2852,x
	lda TransposedFontRow2_3,y
	sta $2c52,x
	lda TransposedFontRow2_4,y
	sta $3052,x
	lda TransposedFontRow2_5,y
	sta $3452,x
	lda TransposedFontRow2_6,y
	sta $3852,x
	lda TransposedFontRow2_7,y
	sta $3c52,x
	lda TransposedFontRow2_8,y
	sta $20d2,x
	lda TransposedFontRow2_9,y
	sta $24d2,x
	lda TransposedFontRow2_10,y
	sta $28d2,x
	lda TransposedFontRow2_11,y
	sta $2cd2,x
	lda TransposedFontRow2_12,y
	sta $30d2,x
	lda TransposedFontRow2_13,y
	sta $34d2,x
	lda TransposedFontRow2_14,y
	sta $38d2,x
	lda TransposedFontRow2_15,y
	sta $3cd2,x
	lda TransposedFontRow2_16,y
	sta $2152,x
	lda TransposedFontRow2_17,y
	sta $2552,x
	lda TransposedFontRow2_18,y
	sta $2952,x
	lda TransposedFontRow2_19,y
	sta $2d52,x
	lda TransposedFontRow2_20,y
	sta $3152,x
	lda TransposedFontRow2_21,y
	sta $3552,x
	lda TransposedFontRow2_22,y
	sta $3952,x
	lda TransposedFontRow2_23,y
	sta $3d52,x
	lda TransposedFontRow2_24,y
	sta $21d2,x
	lda TransposedFontRow2_25,y
	sta $25d2,x
	lda TransposedFontRow2_26,y
	sta $29d2,x
	lda TransposedFontRow2_27,y
	sta $2dd2,x
	lda TransposedFontRow2_28,y
	sta $31d2,x
	lda TransposedFontRow2_29,y
	sta $35d2,x
	lda TransposedFontRow2_30,y
	sta $39d2,x
	lda TransposedFontRow2_31,y
	sta $3dd2,x
	lda TransposedFontRow3_0,y
	sta $2053,x
	lda TransposedFontRow3_1,y
	sta $2453,x
	lda TransposedFontRow3_2,y
	sta $2853,x
	lda TransposedFontRow3_3,y
	sta $2c53,x
	lda TransposedFontRow3_4,y
	sta $3053,x
	lda TransposedFontRow3_5,y
	sta $3453,x
	lda TransposedFontRow3_6,y
	sta $3853,x
	lda TransposedFontRow3_7,y
	sta $3c53,x
	lda TransposedFontRow3_8,y
	sta $20d3,x
	lda TransposedFontRow3_9,y
	sta $24d3,x
	lda TransposedFontRow3_10,y
	sta $28d3,x
	lda TransposedFontRow3_11,y
	sta $2cd3,x
	lda TransposedFontRow3_12,y
	sta $30d3,x
	lda TransposedFontRow3_13,y
	sta $34d3,x
	lda TransposedFontRow3_14,y
	sta $38d3,x
	lda TransposedFontRow3_15,y
	sta $3cd3,x
	lda TransposedFontRow3_16,y
	sta $2153,x
	lda TransposedFontRow3_17,y
	sta $2553,x
	lda TransposedFontRow3_18,y
	sta $2953,x
	lda TransposedFontRow3_19,y
	sta $2d53,x
	lda TransposedFontRow3_20,y
	sta $3153,x
	lda TransposedFontRow3_21,y
	sta $3553,x
	lda TransposedFontRow3_22,y
	sta $3953,x
	lda TransposedFontRow3_23,y
	sta $3d53,x
	lda TransposedFontRow3_24,y
	sta $21d3,x
	lda TransposedFontRow3_25,y
	sta $25d3,x
	lda TransposedFontRow3_26,y
	sta $29d3,x
	lda TransposedFontRow3_27,y
	sta $2dd3,x
	lda TransposedFontRow3_28,y
	sta $31d3,x
	lda TransposedFontRow3_29,y
	sta $35d3,x
	lda TransposedFontRow3_30,y
	sta $39d3,x
	lda TransposedFontRow3_31,y
	sta $3dd3,x
	ldy scratch_0
	rts
FASTFONT_H1_5
	lda TransposedFontRow0_0,y
	sta $2250,x
	lda TransposedFontRow0_1,y
	sta $2650,x
	lda TransposedFontRow0_2,y
	sta $2a50,x
	lda TransposedFontRow0_3,y
	sta $2e50,x
	lda TransposedFontRow0_4,y
	sta $3250,x
	lda TransposedFontRow0_5,y
	sta $3650,x
	lda TransposedFontRow0_6,y
	sta $3a50,x
	lda TransposedFontRow0_7,y
	sta $3e50,x
	lda TransposedFontRow0_8,y
	sta $22d0,x
	lda TransposedFontRow0_9,y
	sta $26d0,x
	lda TransposedFontRow0_10,y
	sta $2ad0,x
	lda TransposedFontRow0_11,y
	sta $2ed0,x
	lda TransposedFontRow0_12,y
	sta $32d0,x
	lda TransposedFontRow0_13,y
	sta $36d0,x
	lda TransposedFontRow0_14,y
	sta $3ad0,x
	lda TransposedFontRow0_15,y
	sta $3ed0,x
	lda TransposedFontRow0_16,y
	sta $2350,x
	lda TransposedFontRow0_17,y
	sta $2750,x
	lda TransposedFontRow0_18,y
	sta $2b50,x
	lda TransposedFontRow0_19,y
	sta $2f50,x
	lda TransposedFontRow0_20,y
	sta $3350,x
	lda TransposedFontRow0_21,y
	sta $3750,x
	lda TransposedFontRow0_22,y
	sta $3b50,x
	lda TransposedFontRow0_23,y
	sta $3f50,x
	lda TransposedFontRow0_24,y
	sta $23d0,x
	lda TransposedFontRow0_25,y
	sta $27d0,x
	lda TransposedFontRow0_26,y
	sta $2bd0,x
	lda TransposedFontRow0_27,y
	sta $2fd0,x
	lda TransposedFontRow0_28,y
	sta $33d0,x
	lda TransposedFontRow0_29,y
	sta $37d0,x
	lda TransposedFontRow0_30,y
	sta $3bd0,x
	lda TransposedFontRow0_31,y
	sta $3fd0,x
	lda TransposedFontRow1_0,y
	sta $2251,x
	lda TransposedFontRow1_1,y
	sta $2651,x
	lda TransposedFontRow1_2,y
	sta $2a51,x
	lda TransposedFontRow1_3,y
	sta $2e51,x
	lda TransposedFontRow1_4,y
	sta $3251,x
	lda TransposedFontRow1_5,y
	sta $3651,x
	lda TransposedFontRow1_6,y
	sta $3a51,x
	lda TransposedFontRow1_7,y
	sta $3e51,x
	lda TransposedFontRow1_8,y
	sta $22d1,x
	lda TransposedFontRow1_9,y
	sta $26d1,x
	lda TransposedFontRow1_10,y
	sta $2ad1,x
	lda TransposedFontRow1_11,y
	sta $2ed1,x
	lda TransposedFontRow1_12,y
	sta $32d1,x
	lda TransposedFontRow1_13,y
	sta $36d1,x
	lda TransposedFontRow1_14,y
	sta $3ad1,x
	lda TransposedFontRow1_15,y
	sta $3ed1,x
	lda TransposedFontRow1_16,y
	sta $2351,x
	lda TransposedFontRow1_17,y
	sta $2751,x
	lda TransposedFontRow1_18,y
	sta $2b51,x
	lda TransposedFontRow1_19,y
	sta $2f51,x
	lda TransposedFontRow1_20,y
	sta $3351,x
	lda TransposedFontRow1_21,y
	sta $3751,x
	lda TransposedFontRow1_22,y
	sta $3b51,x
	lda TransposedFontRow1_23,y
	sta $3f51,x
	lda TransposedFontRow1_24,y
	sta $23d1,x
	lda TransposedFontRow1_25,y
	sta $27d1,x
	lda TransposedFontRow1_26,y
	sta $2bd1,x
	lda TransposedFontRow1_27,y
	sta $2fd1,x
	lda TransposedFontRow1_28,y
	sta $33d1,x
	lda TransposedFontRow1_29,y
	sta $37d1,x
	lda TransposedFontRow1_30,y
	sta $3bd1,x
	lda TransposedFontRow1_31,y
	sta $3fd1,x
	lda TransposedFontRow2_0,y
	sta $2252,x
	lda TransposedFontRow2_1,y
	sta $2652,x
	lda TransposedFontRow2_2,y
	sta $2a52,x
	lda TransposedFontRow2_3,y
	sta $2e52,x
	lda TransposedFontRow2_4,y
	sta $3252,x
	lda TransposedFontRow2_5,y
	sta $3652,x
	lda TransposedFontRow2_6,y
	sta $3a52,x
	lda TransposedFontRow2_7,y
	sta $3e52,x
	lda TransposedFontRow2_8,y
	sta $22d2,x
	lda TransposedFontRow2_9,y
	sta $26d2,x
	lda TransposedFontRow2_10,y
	sta $2ad2,x
	lda TransposedFontRow2_11,y
	sta $2ed2,x
	lda TransposedFontRow2_12,y
	sta $32d2,x
	lda TransposedFontRow2_13,y
	sta $36d2,x
	lda TransposedFontRow2_14,y
	sta $3ad2,x
	lda TransposedFontRow2_15,y
	sta $3ed2,x
	lda TransposedFontRow2_16,y
	sta $2352,x
	lda TransposedFontRow2_17,y
	sta $2752,x
	lda TransposedFontRow2_18,y
	sta $2b52,x
	lda TransposedFontRow2_19,y
	sta $2f52,x
	lda TransposedFontRow2_20,y
	sta $3352,x
	lda TransposedFontRow2_21,y
	sta $3752,x
	lda TransposedFontRow2_22,y
	sta $3b52,x
	lda TransposedFontRow2_23,y
	sta $3f52,x
	lda TransposedFontRow2_24,y
	sta $23d2,x
	lda TransposedFontRow2_25,y
	sta $27d2,x
	lda TransposedFontRow2_26,y
	sta $2bd2,x
	lda TransposedFontRow2_27,y
	sta $2fd2,x
	lda TransposedFontRow2_28,y
	sta $33d2,x
	lda TransposedFontRow2_29,y
	sta $37d2,x
	lda TransposedFontRow2_30,y
	sta $3bd2,x
	lda TransposedFontRow2_31,y
	sta $3fd2,x
	lda TransposedFontRow3_0,y
	sta $2253,x
	lda TransposedFontRow3_1,y
	sta $2653,x
	lda TransposedFontRow3_2,y
	sta $2a53,x
	lda TransposedFontRow3_3,y
	sta $2e53,x
	lda TransposedFontRow3_4,y
	sta $3253,x
	lda TransposedFontRow3_5,y
	sta $3653,x
	lda TransposedFontRow3_6,y
	sta $3a53,x
	lda TransposedFontRow3_7,y
	sta $3e53,x
	lda TransposedFontRow3_8,y
	sta $22d3,x
	lda TransposedFontRow3_9,y
	sta $26d3,x
	lda TransposedFontRow3_10,y
	sta $2ad3,x
	lda TransposedFontRow3_11,y
	sta $2ed3,x
	lda TransposedFontRow3_12,y
	sta $32d3,x
	lda TransposedFontRow3_13,y
	sta $36d3,x
	lda TransposedFontRow3_14,y
	sta $3ad3,x
	lda TransposedFontRow3_15,y
	sta $3ed3,x
	lda TransposedFontRow3_16,y
	sta $2353,x
	lda TransposedFontRow3_17,y
	sta $2753,x
	lda TransposedFontRow3_18,y
	sta $2b53,x
	lda TransposedFontRow3_19,y
	sta $2f53,x
	lda TransposedFontRow3_20,y
	sta $3353,x
	lda TransposedFontRow3_21,y
	sta $3753,x
	lda TransposedFontRow3_22,y
	sta $3b53,x
	lda TransposedFontRow3_23,y
	sta $3f53,x
	lda TransposedFontRow3_24,y
	sta $23d3,x
	lda TransposedFontRow3_25,y
	sta $27d3,x
	lda TransposedFontRow3_26,y
	sta $2bd3,x
	lda TransposedFontRow3_27,y
	sta $2fd3,x
	lda TransposedFontRow3_28,y
	sta $33d3,x
	lda TransposedFontRow3_29,y
	sta $37d3,x
	lda TransposedFontRow3_30,y
	sta $3bd3,x
	lda TransposedFontRow3_31,y
	sta $3fd3,x
	ldy scratch_0
	rts

TransposedFontRow0_0
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_0
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_0
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_0
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_1
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_1
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_1
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_1
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_2
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_2
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_2
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_2
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_3
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_3
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_3
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_3
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_4
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_4
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_4
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_4
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_5
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_5
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_5
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_5
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_6
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_6
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_6
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_6
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_7
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_7
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_7
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_7
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_8
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_8
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_8
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_8
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_9
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_9
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_9
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_9
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_10
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_10
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_10
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_10
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_11
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_11
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_11
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_11
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_12
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_12
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_12
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_12
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_13
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_13
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_13
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_13
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_14
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_14
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_14
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_14
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_15
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_15
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_15
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_15
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_16
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_16
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_16
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_16
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_17
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_17
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_17
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_17
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_18
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_18
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_18
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_18
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_19
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_19
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_19
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_19
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_20
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_20
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_20
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_20
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_21
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_21
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_21
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_21
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_22
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_22
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_22
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_22
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_23
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_23
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_23
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_23
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_24
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_24
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_24
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_24
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_25
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_25
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_25
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_25
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_26
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_26
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_26
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_26
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_27
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_27
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_27
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_27
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_28
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_28
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_28
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_28
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_29
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_29
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_29
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_29
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_30
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_30
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_30
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_30
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow0_31
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow1_31
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow2_31
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f
TransposedFontRow3_31
	.byte $00, $01, $02, $03, $04, $05, $06, $07, $08, $09, $0a, $0b, $0c, $0d, $0e, $0f

